name: Create New Release

description: Create New Release

inputs:
  tag:
    required: true
    description: tag

runs:
  using: "composite"
  steps:
    - name: Git checkout
      uses: actions/checkout@v3
      with:
        ref: "main"

    - name: git
      run: |
        git checkout -b "rc/${{ inputs.tag }}"
        git push --set-upstream origin "rc/${{ inputs.tag }}"

    - name: Send Message to Slack
      uses: 8398a7/action-slack@v3
      with:
        status: ${{job.status}}
        username: "CREATE_RC|${{github.event.repository.name}}|rc/${{ inputs.tag }}"
        author_name: ${{github.workflow}}
        fields: repo,message,commit,author,action,eventName,ref,workflow,job,took,pullRequest
      if: always()
