name: Create New Release

description: Create New Release

inputs:
  tag:
    required: true
    description: tag

runs:
  using: "composite"
  steps:
    
    - name: Checkout
      uses: actions/checkout@v3
    
    - name: Updating release branch
      run: |
        git config user.name "GitHub Actions Bot"
        git config user.email "devops@atarb2b.com"
        git fetch --all
        git checkout rc/${{ inputs.tag }}
        git pull
        git checkout -b release/${{ inputs.tag }}
        git push --set-upstream origin release/${{ inputs.tag }}
        gh release edit ${{ inputs.tag }} --prerelease=false
      shell: bash
    
    - name: Delete RC Branch
      run: git push origin --delete "rc/${{ inputs.tag }}"
      shell: bash
